spring.application.name=wecureit_be
spring.profiles.active=prod

# ---- Local KMS / Encryption Config ----
wecureit.keystore.path=keys/wecureit-keystore.jceks
wecureit.keystore.password=StrongPassword123!
wecureit.key.alias=wecureitMasterKey



